### ISSUE TITLE
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.

### ISSUE THREAD

**Issue by cbergstrom** [kirei/fpdns#11]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

 perl --version

This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-gnu-thread-multi
(with 56 registered patches, see perl -V for more detail)

apps/fpdns -D foobar.com
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.

**Comment by digitalist** [comment]
same on 18.04 I wonder if there are any perl-gurus left like @krautcat maybe

**Comment by krautcat** [comment]
Seems it's bug in `Net::DNS` library. Can anyone test _this_ package under earlier version of `Net::DNS` library?

**Comment by digitalist** [comment]
well I can say fpdns works (more or less and without this error) on xenial (tested in docker tho)

**Comment by wessels** [comment]
Should be eliminated now with https://github.com/kirei/fpdns/commit/3e7fc5fc3267e58ce30d82806ef001e4064b5da2

**Comment by TrevinAvery** [comment]
I am using the most recent version which includes the changes from 3e7fc5f, but I am still getting the same error.

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

perl --version

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)

apps/fpdns -v
fpdns version 0.10.0

apps/fpdns -D foobar.com
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
fingerprint (foobar.com, 70.39.150.2): No match found  
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.
fingerprint (foobar.com, 74.124.210.242): No match found

**Comment by wessels** [comment]
I bumped the version on Fingerprint.pm just now, since it hadn't been updated in a long time.  
Can you reinstall the latest and see if fpdns -v now reports 0.11.0 instead?  I'm worried that maybe you have Fingerprint.pm installed in different places and its picking up the old version.

**Comment by TrevinAvery** [comment]
I tried updating the version from apt, no change

sudo apt update
sudo apt upgrade
fpdns -v
fpdns version 0.10.0
which fpdns
/usr/bin/fpdns

And I updated the version from the current master
git pull
git branch
* master
./apps/fpdns -v
fpdns version 0.10.0

Also getting the same error.

**Comment by wessels** [comment]
The version information comes from the Fingerprint.pm module file.  You will have to 'make install' from the latest git copy.

**Comment by TrevinAvery** [comment]
I was able to build and install the git version with

perl Makefile.PL
sudo make install

It appears to be working just fine now. It would be great to get this newer version in apt.
