### ISSUE TITLE
Odd result when running on ipv4 address

### ISSUE THREAD

**Issue by Uberhumus** [kirei/fpdns#12]
When running `fpdns 8.8.8.8` I get:
`Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 986.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 987.

Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/DNS/Resolver/Base.pm line 988.

fingerprint (8.8.8.8, 8.8.8.8): No match found`

I get a similar result when running it on our internal DNS servers.

**Comment by wessels** [comment]
The 'Use of uninitialized value' errors should be silenced with this commit https://github.com/kirei/fpdns/commit/3e7fc5fc3267e58ce30d82806ef001e4064b5da2
