### ISSUE TITLE
Can't call method "zclass" on an undefined value at /usr/lib64/perl5/vendor_perl/5.16.3/x86_64-linux/Net/DNS/Packet.pm line 472.

### ISSUE THREAD

**Issue by wschlich** [kirei/fpdns#8]
zephyr ~ # fpdns -Df isc.org
fingerprint (isc.org, 199.6.1.30): No match found
fingerprint (isc.org, 2001:500:60:0:0:0:0:30): No match found
Can't call method "zclass" on an undefined value at /usr/lib64/perl5/vendor_perl/5.16.3/x86_64-linux/Net/DNS/Packet.pm line 472.
zephyr ~ # qlist -Iv =dev-perl/Net-DNS
dev-perl/Net-DNS-0.740.0
zephyr ~ # qlist -Iv =net-dns/fpdns
net-dns/fpdns-0.10.0_pre20130404
zephyr ~ #

**Comment by stasic** [comment]
for me it works with the latest fpdns release (20 Nov 2013)

perl -MNet::DNS::Fingerprint -e 'print $Net::DNS::Fingerprint::VERSION';
0.10.0

perl -MNet::DNS -e 'print $Net::DNS::VERSION';
0.81

fpdns -Df isc.org
fingerprint (isc.org, 199.6.1.30): No match found  
fingerprint (isc.org, 2001:500:60:0:0:0:0:30): No match found  
fingerprint (isc.org, 149.20.64.3): No match found  
fingerprint (isc.org, 2001:4f8:0:2:0:0:0:19): No match found  
fingerprint (isc.org, 199.6.0.30): No match found  
fingerprint (isc.org, 2001:500:71:0:0:0:0:30): No match found  
fingerprint (isc.org, 199.254.63.254): No match found  
fingerprint (isc.org, 2001:500:2c:0:0:0:0:254): No match found  

Do you still have this issue?

**Comment by jtkdpu** [comment]
I see this issue and I've got the latest code as of today.

$ perl -MNet::DNS::Fingerprint -e 'print $Net::DNS::Fingerprint::VERSION';
0.10.0
$ perl -MNet::DNS -e 'print $Net::DNS::VERSION';
0.83

The isc.org test won't exhibit it.  Here is an example host I got it on:

$ fpdns -Df 36.230.129.160

I've not yet captured the packets that may have exhibited this, so hopefully this host example is enough for now that someone else can reproduce it.  If not, let me know and I'll do some further digging.

**Comment by wessels** [comment]
This looks to me like a bug in Net::DNS.  I will ask on the net-dns-users list.  Here is a small program which demonstrates the bug

#!/usr/bin/perl
use strict;
use warnings;
use Net::DNS::Packet;

my $packet = new Net::DNS::Packet;
my $q  = new Net::DNS::Question('.', 'IN', 'A');

$packet->header->opcode('UPDATE');
$packet->push('question', $q);

**Comment by wessels** [comment]
Bug filed with Net::DNS

https://rt.cpan.org/Public/Bug/Display.html?id=105491

**Comment by stedaniels** [comment]
This has been resolved in Net::DNS.
